#!/usr/bin/env bash
# This script prints "Best School" 10 times, but prints "Hi" after the 9th time

count=1
while [ $count -le 10 ]
do
  echo "Best School"
  if [ $count -eq 9 ]; then
    echo "Hi"
  fi
  count=$((count + 1))
done
